[package]
name = "miditest"
version = "0.1.0"
authors = ["Jade Bilkey <herself@thefumon.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
midi-msg = "0.3.0"
midir = "0.7.0"
dialoguer = "0.8.0"